"""
clustering.py
--------------
Groups countries by gender-inequality / health-outcome profile using
K-means.

Same pattern as the healthcare-expenditure dashboard: standardized
features, k chosen by silhouette score (not fixed by hand), and cluster
labels generated by comparing each centroid against the global median.
"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler


def select_k(features_scaled: np.ndarray, k_range: range = range(2, 7)) -> tuple[int, dict]:
    scores = {}
    for k in k_range:
        if k >= len(features_scaled):
            continue
        model = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = model.fit_predict(features_scaled)
        scores[k] = silhouette_score(features_scaled, labels)

    if not scores:
        raise ValueError("Could not evaluate any k value: too few observations.")

    best_k = max(scores, key=scores.get)
    return best_k, scores


def run_clustering(
    df: pd.DataFrame,
    outcome_col: str = "maternal_mortality_ratio",
    indicator_col: str = "gii",
    k: int | None = None,
) -> tuple[pd.DataFrame, dict]:
    """
    Runs K-means over [inequality_indicator, log(maternal_mortality)]
    for rows with complete data.
    """
    df = df.copy()
    valid_mask = (
        df[outcome_col].notna()
        & df[indicator_col].notna()
        & (df[outcome_col] > 0)
    )
    subset = df.loc[valid_mask]

    if len(subset) < 10:
        raise ValueError("Not enough observations for clustering (minimum 10).")

    features = np.column_stack([
        subset[indicator_col].values,
        np.log(subset[outcome_col].values),
    ])
    scaler = StandardScaler()
    features_scaled = scaler.fit_transform(features)

    silhouette_scores = None
    if k is None:
        k, silhouette_scores = select_k(features_scaled)

    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = model.fit_predict(features_scaled)

    df["cluster"] = np.nan
    df.loc[valid_mask, "cluster"] = cluster_labels

    label_map = _interpret_clusters(subset, cluster_labels, outcome_col, indicator_col)
    df["cluster_label"] = df["cluster"].map(label_map)

    metadata = {
        "k": k,
        "silhouette_scores": silhouette_scores,
        "label_map": label_map,
    }
    return df, metadata


def _interpret_clusters(
    subset: pd.DataFrame, cluster_labels: np.ndarray, outcome_col: str, indicator_col: str
) -> dict:
    """
    Generates readable labels by comparing each cluster's median against
    the global median, on the two dimensions used for clustering.

    KNOWN LIMITATION: this scheme uses a binary (high/low) threshold
    against the GLOBAL median, not against the other clusters. With
    k > 2 this can produce two distinct clusters with the SAME label
    (e.g. two groups that both fall "below the global median" but that
    K-means separated for another reason — typically within-quadrant
    spread). This is a deliberate simplification to keep labels readable
    without combinatorial cross-cluster comparison logic; if two clusters
    share a label, check the per-cluster country count/list to tell them
    apart rather than assuming they're the same group.
    """
    median_indicator = subset[indicator_col].median()
    median_outcome = subset[outcome_col].median()
    indicator_label = "GII" if indicator_col == "gii" else "GDI"

    label_map = {}
    for cluster_id in np.unique(cluster_labels):
        mask = cluster_labels == cluster_id
        cluster_indicator = subset.loc[mask, indicator_col].median()
        cluster_outcome = subset.loc[mask, outcome_col].median()

        indicator_tag = f"High {indicator_label}" if cluster_indicator > median_indicator else f"Low {indicator_label}"
        outcome_tag = "high maternal mortality" if cluster_outcome > median_outcome else "low maternal mortality"
        label_map[float(cluster_id)] = f"{indicator_tag}, {outcome_tag}"

    return label_map
